wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
dim:
  desc: null
  value: '128'
dataset:
  desc: null
  value: 1m
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.5
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711962459.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.19
      5: 0.16.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
