wandb_version: 1

dataset_name:
  desc: null
  value: 1m
embed_size:
  desc: null
  value: 1024
n_layers:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 4096
decay:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 40
eval_epoch:
  desc: null
  value: -1
learning_rate:
  desc: null
  value: 0.0025
top_k:
  desc: null
  value: 20
create_time:
  desc: null
  value: 2024-04-02_10-12-15
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.5
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712023936.0
    t:
      1:
      - 2
      - 3
      - 5
      - 8
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 8
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
