wandb_version: 1

dataset_name:
  desc: null
  value: 1m
embed_size:
  desc: null
  value:
  - 1024
  - 256
n_layers:
  desc: null
  value:
  - 1
  - 2
  - 3
  - 4
batch_size:
  desc: null
  value:
  - 50000
  - 10000
decay:
  desc: null
  value:
  - 0.01
  - 0.001
epochs:
  desc: null
  value:
  - 40
eval_epoch:
  desc: null
  value: '1'
learning_rate:
  desc: null
  value:
  - 0.01
  - 0.05
top_k:
  desc: null
  value: '20'
create_time:
  desc: null
  value: 2024-04-02_10-13-55
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.5
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712024037.0
    t:
      1:
      - 2
      - 3
      - 5
      - 8
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 8
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
